import crypto from 'node:crypto';
import path from 'node:path';
import { latticeHomeDir } from '../projectPath.js';

// `~/.lattice/callback-outbox/` — one JSON file per undelivered completion
// callback. Home-scoped (never inside a project tree) so a worktree teardown
// can't take a pending callback down with it.
export function callbackOutboxDir(): string {
  return path.join(latticeHomeDir(), 'callback-outbox');
}

// `~/.lattice/bin/lattice-callback.cjs` — the delivery script every Claude /
// Codex Stop hook runs. Regenerated by the backend (boot + every hook
// install), so its code always matches the drain it cooperates with.
export function callbackScriptPath(): string {
  return path.join(latticeHomeDir(), 'bin', 'lattice-callback.cjs');
}

// One entry per callback URL: a Claude Stop hook fires on EVERY turn end, so
// keying by URL collapses repeats into the newest one instead of queueing a
// replay per turn. The generated script and the Pi extension compute the same
// key (sha1 hex, first 20 chars) — keep them in step with this function.
export function callbackOutboxKey(url: string): string {
  return crypto.createHash('sha1').update(url).digest('hex').slice(0, 20);
}

export function callbackOutboxEntryPath(url: string, dir = callbackOutboxDir()): string {
  return path.join(dir, `${callbackOutboxKey(url)}.json`);
}
