import fs from 'node:fs';
import path from 'node:path';
import { callbackOutboxDir, callbackScriptPath } from './paths.js';

// The delivery script behind every Claude / Codex Stop hook.
//
// It used to be a bare `curl -s -m 5 -X POST <url>`: one attempt, five
// seconds. When Lattice works on its own repo, every merge that touches
// `backend/src` restarts the backend, and a Stop that fired inside that
// window was simply gone — the task sat `in_progress` beside an idle
// terminal forever, a re-adopted workflow step never advanced, and nothing
// swept it up (the in-progress sweep only acts on a DEAD pty; an interactive
// Claude stays alive after its turn).
//
// So the hook now writes the callback to a durable OUTBOX first, then tries
// to deliver it for a bounded budget. Delivered (or definitively refused) →
// the entry is removed. Still undeliverable when the budget runs out → the
// entry stays, and the backend replays it once it is back
// (`drain.ts` `drainCallbackOutbox`). Every callback endpoint it targets is
// idempotent, so a replay that races a late original delivery is harmless.
//
// The script is plain CommonJS with no dependencies (it runs under whatever
// `node` the pty's PATH resolves) and always exits 0 without printing:
// a Stop hook's stdout/exit code are interpreted by the harness, and a
// completion callback must never read as "block the stop".

// How long the hook keeps retrying before leaving the entry to the backend.
// Covers a typical dev-runner restart (compile already done, boot ~5-20 s)
// without holding the agent's Stop for long. Keep it under the hook timeout
// below.
export const CALLBACK_HOOK_BUDGET_MS = 45_000;
// Claude / Codex hook `timeout` (seconds) for the Stop hook running the
// script — the harness default (60 s) is too close to the budget above.
export const CALLBACK_HOOK_TIMEOUT_S = 75;
// Per-attempt cap. Generous: a merge-resolver's `/complete` finalizes the merge
// (fast-forward + cleanup) inside the request.
const ATTEMPT_TIMEOUT_MS = 20_000;
const RETRY_DELAY_MS = 1_500;
// The drain leaves an entry alone until the hook that wrote it has given up,
// so the two never deliver the same callback concurrently. The hold written up
// front covers the worst case (the last attempt starting just inside the
// budget and running its full timeout) for a hook that is killed mid-retry;
// a hook that gives up normally releases it at once (below), so its replay
// isn't pushed ~25 s past the moment the hook stopped trying — a window in
// which the backend is back and the user can already be typing into the agent.
const HOLD_GRACE_MS = 5_000;

// `timing` exists for tests (a 45 s budget is no fun to wait out).
export function renderCallbackScript(
  outboxDir = callbackOutboxDir(),
  timing: { budgetMs?: number; retryDelayMs?: number } = {},
): string {
  return `#!/usr/bin/env node
// Lattice-managed — regenerated by the Lattice backend; edits are overwritten.
// Delivers one completion callback: records it in the outbox, POSTs it with
// retries, and leaves it for the backend to replay if it can't get through.
// Usage: node lattice-callback.cjs <callback-url>
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const OUTBOX_DIR = ${JSON.stringify(outboxDir)};
const BUDGET_MS = ${timing.budgetMs ?? CALLBACK_HOOK_BUDGET_MS};
const ATTEMPT_TIMEOUT_MS = ${ATTEMPT_TIMEOUT_MS};
const RETRY_DELAY_MS = ${timing.retryDelayMs ?? RETRY_DELAY_MS};
const HOLD_GRACE_MS = ${HOLD_GRACE_MS};

const url = process.argv[2];
const key = url ? crypto.createHash('sha1').update(url).digest('hex').slice(0, 20) : '';
const file = path.join(OUTBOX_DIR, key + '.json');

function writeEntry(entry) {
  try {
    fs.mkdirSync(OUTBOX_DIR, { recursive: true });
    const tmp = file + '.' + process.pid + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(entry, null, 2));
    fs.renameSync(tmp, file);
  } catch {
    // Best-effort — the POST below still runs.
  }
}

function readEntry() {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

// Giving up: hand the entry to the drain NOW. Only our own entry — a newer
// Stop for the same URL may have replaced it (that hook still holds it), and
// the drain or the backend's ack may already have removed it. The temp file
// is written before the re-check so the rename is all that follows it.
function releaseHold(createdAt) {
  try {
    const current = readEntry();
    if (!current || current.createdAt !== createdAt) return;
    current.holdUntil = Date.now();
    const tmp = file + '.' + process.pid + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(current, null, 2));
    const again = readEntry();
    if (!again || again.createdAt !== createdAt) {
      fs.unlinkSync(tmp);
      return;
    }
    fs.renameSync(tmp, file);
  } catch {
    // Best-effort — the original hold still expires on its own.
  }
}

function removeEntry() {
  try {
    fs.unlinkSync(file);
  } catch {
    // Already gone (the backend replayed it) — fine.
  }
}

// 2xx is delivered; any other 4xx is a definitive answer (unknown task,
// stale step) that a retry can't change. 5xx / 408 / 429 / network → retry.
function isFinal(status) {
  return status < 500 && status !== 408 && status !== 429;
}

// node:http rather than global fetch: this runs under whatever \`node\` the
// pty's PATH resolves, and fetch only exists from Node 18 — on an older node
// every attempt would fail and each callback would wait for the drain.
function attempt() {
  return new Promise((resolve) => {
    let settled = false;
    const done = (status) => { if (!settled) { settled = true; resolve(status); } };
    let req;
    try {
      const u = new URL(url);
      const client = require(u.protocol === 'https:' ? 'https' : 'http');
      req = client.request(u, { method: 'POST', headers: { 'content-length': 0 } }, (res) => {
        res.resume();
        res.on('end', () => done(res.statusCode ?? null));
        res.on('error', () => done(res.statusCode ?? null));
        res.on('close', () => done(res.statusCode ?? null));
      });
    } catch {
      done(null);
      return;
    }
    req.setTimeout(ATTEMPT_TIMEOUT_MS, () => req.destroy());
    req.on('error', () => done(null));
    req.end();
  });
}

async function main() {
  if (!url) return;
  const startedAt = Date.now();
  writeEntry({
    v: 1,
    url,
    createdAt: startedAt,
    holdUntil: startedAt + BUDGET_MS + ATTEMPT_TIMEOUT_MS + HOLD_GRACE_MS,
    attempts: 0,
    writer: 'hook',
  });
  for (;;) {
    const status = await attempt();
    if (status !== null && isFinal(status)) {
      removeEntry();
      return;
    }
    if (Date.now() - startedAt + RETRY_DELAY_MS >= BUDGET_MS) {
      releaseHold(startedAt);
      return;
    }
    await new Promise((r) => setTimeout(r, RETRY_DELAY_MS));
  }
}

main().catch(() => {}).finally(() => process.exit(0));
`;
}

// Write the script if it is missing or out of date. Synchronous on purpose:
// it is called from the hook renderers' install paths and from boot, and a
// hook must never be installed pointing at a script that isn't there yet.
// Atomic (temp + rename) so a hook firing mid-write never runs half a file.
export function ensureCallbackScript(
  file = callbackScriptPath(),
  outboxDir = callbackOutboxDir(),
): void {
  const expected = renderCallbackScript(outboxDir);
  try {
    if (fs.readFileSync(file, 'utf8') === expected) return;
  } catch {
    /* absent — write it */
  }
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, expected, 'utf8');
    fs.renameSync(tmp, file);
  } catch (err) {
    // Non-fatal: the Claude hook falls back to a retrying curl when node
    // can't load the script, and the Codex hook's model curl still exists.
    console.warn(`[callback-outbox] could not write ${file}:`, err);
  }
}

// A curl that rides out a backend restart on its own: `--retry-connrefused`
// covers the port being closed, `--retry` the 503 a recovering backend
// answers with. Used where the script can't be (see the builders below).
export function retryingCurl(url: string, quote: boolean): string {
  const target = quote ? `"${url}"` : url;
  return `curl -s -m 20 --retry 15 --retry-delay 3 --retry-connrefused -X POST ${target}`;
}

// Forward slashes: valid on Windows for node, and immune to both bash's and
// JSON's backslash handling.
function scriptPathForShell(): string {
  return callbackScriptPath().replace(/\\/g, '/');
}

// Claude runs a hook command through a shell (bash, or cmd on a bare Windows
// setup — `||` and double quotes mean the same in both). The `||` fallback
// fires only when node itself can't run the script (not on PATH, file
// missing): the script always exits 0 otherwise, including when it left the
// callback for the backend to replay.
export function claudeCallbackCommand(url: string): string {
  return `node "${scriptPathForShell()}" "${url}" || ${retryingCurl(url, true)}`;
}

// Codex whitespace-splits a hook command and spawns the argv directly — no
// shell, no quote stripping (see codexStopHook.ts). So: no quotes, no `||`,
// and a script path containing whitespace (a home dir with a space) can't be
// expressed at all — that case falls back to the retrying curl.
export function codexCallbackCommands(url: string): { posix: string; windows: string } {
  const script = scriptPathForShell();
  const posix = /\s/.test(script) ? retryingCurl(url, false) : `node ${script} ${url}`;
  return { posix, windows: `cmd /c ${posix}` };
}
