// WORKFLOW_STEP.md — the brief for an agent step in a workflow run. Leaf
// module: array-joined (the body is dense with backticks/fences) plain markdown
// with `{{token}}` placeholders. See ../defs.ts for the catalog entry (token
// docs) and ../CLAUDE.md for the subsystem overview.

export const DEFAULT_WORKFLOW_STEP_TEMPLATE = [
  '# Workflow Step {{step_number}} of {{total_steps}}: {{step_title}}',
  '',
  '{{dirty_state_warning}}',
  '## Your Task',
  '',
  '{{autonomy_preamble}}{{step_prompt}}',
  '',
  '## Active project (use ONLY this one)',
  '',
  '`{{project_path}}`',
  '',
  'Every Lattice API call you make must be for this project. The helper',
  'script below has the project baked in — prefer it over raw curl so you',
  "can't accidentally hit a different project's board. If you do use curl,",
  "verify the response's `canonicalProject` field matches the path above",
  'before acting on the data.',
  '',
  '## Reading the board — query the API, not local files',
  '',
  'The live task DB is the API. **Do not read `tasks.json`, `tasks-current.json`,',
  '`combined-tasks.json`, `lattice_tasks.json`, or any similar file you find',
  'in this directory or sibling workflow-step directories** — those are stale',
  'scratch dumps left by previous agents and they will mislead you (the canonical',
  "example: they often miss whole lanes like 'qa' or 'ready_to_merge'). Always",
  "use `node create-task.cjs --list` or the API; that's the source of truth.",
  '',
  '{{harness_override_note}}You can inspect the project files at that path if helpful.',
  'Your primary role here is to create tasks on the Lattice board so that',
  'code agents can do the implementation work. Do not write or commit code directly.',
  '',
  '## Creating tasks — use the helper script',
  '',
  'A `create-task.cjs` script is in this directory. It handles JSON serialization',
  "for you so you never need to escape quotes, backticks, or special characters,",
  "and every command targets only this project's board.",
  '',
  '**Single task (inline description):**',
  '```bash',
  'node create-task.cjs "Task title" "Short description here"',
  '```',
  '',
  '**Single task with a long/complex description (write to a file first):**',
  '```bash',
  "cat > desc.md << 'EOF'",
  'Your description here. Backticks `like this`, quotes "like this",',
  'and even (parentheses) are all fine inside a single-quoted heredoc.',
  'EOF',
  'node create-task.cjs "Task title" < desc.md',
  '```',
  '',
  '**Multiple tasks at once (recommended when creating 3+ tasks):**',
  '```bash',
  "cat > tasks.json << 'EOF'",
  '[',
  '  { "title": "First task",  "description": "What to do" },',
  '  { "title": "Second task", "description": "Details..." }',
  ']',
  'EOF',
  'node create-task.cjs --batch tasks.json',
  '```',
  '',
  '### Read the board (always project-safe)',
  '```bash',
  'node create-task.cjs --list                  # every task on this project',
  'node create-task.cjs --list open             # one lane',
  'node create-task.cjs --list open,in_progress # multiple lanes',
  'node create-task.cjs --summary               # counts by status',
  '```',
  '',
  'If you ever need a raw curl, the response is an envelope — assert',
  '`.canonicalProject` matches the project path above before iterating',
  '`.tasks`:',
  '',
  '```bash',
  'curl -s "{{backend_origin}}/api/tasks?project={{project_path_encoded}}"',
  '# → { project, canonicalProject, hash, count, mismatched, tasks: [...] }',
  '```',
  '',
  '## When you are done',
  '',
  '{{completion_instructions}}',
].join('\n');
