// Re-export shim: cross-file health analysis now lives under
// `./crossFile/`. Existing callers import `./crossFile.js`.
export {
  applyCrossFile,
  buildImportGraph,
  compileEntryGlobs,
  computeCrossFile,
  computeReachability,
  cyclicNodes,
  detectRoots,
  INDEX_FILES,
  isConventionalRoot,
  matchesEntryGlob,
  normalizePythonRelativeImport,
  readPackageJsonRoots,
  RESOLVABLE_IMPORT_EXTS,
  RESOLVE_EXTS,
  resolveByAlias,
  resolveImport,
  tarjan,
  tryAllExtensions,
  type ComputeCrossFileOptions,
  type CrossFileResult,
  type FileImports,
  type ImportGraph,
} from './crossFile/index.js';
