// The API docs are generated by the MAIN backend at the spawn chokepoint, not
// by the detached terminal-server (which only looks the doc up for its banner):
// the generator + templates change with every API edit, and anything in the
// terminal-server's import graph is fingerprinted — each edit used to mark the
// live executor stale. See latticeApiDocs/docPath.ts.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { resolveHarnessSpawnBody } from '../terminalServerClient/createSession.js';
import { existingLatticeApiDocPath } from '../latticeApiDocs/docPath.js';
import { FINGERPRINT_FILES } from '../terminalFingerprint.js';

test('resolveHarnessSpawnBody writes the project API doc the terminal-server banner names', async () => {
  const project = await fs.mkdtemp(path.join(os.tmpdir(), 'lattice-docrefresh-'));
  try {
    await fs.mkdir(path.join(project, '.lattice'));
    assert.equal(existingLatticeApiDocPath(project), null);
    await resolveHarnessSpawnBody({ cwd: project, projectPath: project });
    const doc = existingLatticeApiDocPath(project);
    assert.ok(doc, 'the doc exists before the pty is requested');
    assert.match(await fs.readFile(doc, 'utf8'), /127\.0\.0\.1/);
  } finally {
    await fs.rm(project, { recursive: true, force: true });
  }
});

test('a project without .lattice/ gets no doc, and the generator is not fingerprinted', async () => {
  const project = await fs.mkdtemp(path.join(os.tmpdir(), 'lattice-docrefresh-'));
  try {
    await resolveHarnessSpawnBody({ cwd: project, projectPath: project });
    assert.equal(existingLatticeApiDocPath(project), null);
    await assert.rejects(fs.stat(path.join(project, '.lattice')));
  } finally {
    await fs.rm(project, { recursive: true, force: true });
  }
  assert.ok(!FINGERPRINT_FILES.some((f) => f === 'latticeApiDocs.js' || f.endsWith('.template.md')));
});
