// The starter `.gitignore` Lattice writes when it initializes a repo.
//
// Composed from things that already exist rather than a hand-written list:
// the always-generated dirs the scanner already refuses to walk
// (`IGNORE_DIR_NAMES`), the entries every Lattice project needs
// (`LATTICE_GITIGNORE_ENTRIES`), and — the part that makes this worth
// generating per project — the heavy dirs of the toolchains actually detected
// in THIS folder (`detectProjectEnvironments`). That last one is why we don't
// blanket-ignore `target/`, `bin/` or `obj/`: they are build output for Rust /
// Maven / .NET but perfectly ordinary source directories in a JS project, and
// silently dropping a source tree out of the first commit is much worse than
// an over-large one the user can see in the preview.

import {
  detectProjectEnvironments,
  type DetectedEnv,
} from '../worktree/envDetect.js';
import { IGNORE_DIR_NAMES } from '../health/constants.js';
import { LATTICE_GITIGNORE_ENTRIES } from '../worktree/managedFiles.js';

// Dirs from IGNORE_DIR_NAMES that only earn an ignore when we've *detected*
// the ecosystem that generates them (see the header). `bin`/`obj`/`vendor` are
// in the same class but never appear in IGNORE_DIR_NAMES, so they can only
// arrive via detection anyway.
const ECOSYSTEM_SCOPED_DIRS = new Set(['target']);

// Editor state reads better under the noise heading than under build output.
const EDITOR_DIRS = ['.idea', '.vscode'];

const BUILD_DIRS = [...IGNORE_DIR_NAMES]
  .filter(
    (name) =>
      name !== '.git' &&
      !EDITOR_DIRS.includes(name) &&
      !ECOSYSTEM_SCOPED_DIRS.has(name),
  )
  .sort();

const SECRET_PATTERNS = [
  '.env',
  '.env.*',
  '*.pem',
  '*.key',
  '*.p12',
  '*.pfx',
  'credentials.json',
];

const NOISE_PATTERNS = [
  '.DS_Store',
  'Thumbs.db',
  '*.swp',
  ...EDITOR_DIRS.map((d) => `${d}/`),
];

const HEADER = [
  '# .gitignore generated by Lattice when it set up this repository.',
  "# It's a starting point, not a rule — edit or delete anything here, then",
  '# re-check the file count before the first commit.',
].join('\n');

type Section = { title: string; entries: string[] };

function renderSections(sections: Section[]): string {
  const seen = new Set<string>();
  const out: string[] = [HEADER];
  for (const section of sections) {
    const entries = section.entries.filter((e) => e && !seen.has(e));
    if (entries.length === 0) continue;
    for (const entry of entries) seen.add(entry);
    out.push('', `# ${section.title}`, ...entries);
  }
  return `${out.join('\n')}\n`;
}

function detectedSection(detected: DetectedEnv[]): Section {
  const labels = [...new Set(detected.map((env) => env.label))];
  return {
    title: `Heavy directories for the toolchains detected here (${labels.join(', ')})`,
    entries: [...new Set(detected.map((env) => `${env.heavyDir}/`))],
  };
}

export async function buildStarterGitignore(repoRoot: string): Promise<string> {
  // Detection is a best-effort read of the folder; a failure should cost the
  // project-specific section, never the whole file.
  let detected: DetectedEnv[] = [];
  try {
    detected = await detectProjectEnvironments(repoRoot);
  } catch (err) {
    console.warn('[projectInit] environment detection failed:', err);
  }

  return renderSections([
    {
      title: 'Lattice scratch and agent state',
      entries: [...LATTICE_GITIGNORE_ENTRIES],
    },
    {
      title: 'Dependencies, build output, and tool caches',
      entries: BUILD_DIRS.map((d) => `${d}/`),
    },
    ...(detected.length > 0 ? [detectedSection(detected)] : []),
    { title: 'Secrets — keep these out of history', entries: SECRET_PATTERNS },
    { title: 'Editor and OS noise', entries: NOISE_PATTERNS },
  ]);
}
