// The ONLY place third-party Opengrep material is named in the Lattice repo:
// a pinned engine version with per-asset SHA-256 digests, and the rule packs
// with their pinned commits and licences. Nothing here is a binary or a rule
// file — Lattice stays MIT because the engine (LGPL-2.1) and every rule pack are
// runtime downloads into `~/.lattice/opengrep/` made at the user's explicit
// click, executed as a separate process, never committed, bundled or
// redistributed (see ./CLAUDE.md, "Licence boundary").
//
// Bumping the engine: run `node scripts/opengrep-pin.mjs <tag>` from the repo
// root. It downloads every release asset, verifies each Sigstore signature with
// `cosign verify-blob` against the Opengrep release workflow identity below,
// and rewrites the block between the `<opengrep-pin:assets>` markers. It
// REFUSES to write digests it could not verify, so a user installing from these
// pins inherits the signature check the maintainer performed — without needing
// cosign themselves. Never edit the digest block by hand.

export const OPENGREP_VERSION = '1.30.0';
export const OPENGREP_RELEASE_TAG = `v${OPENGREP_VERSION}`;
export const OPENGREP_RELEASE_BASE_URL =
  `https://github.com/opengrep/opengrep/releases/download/${OPENGREP_RELEASE_TAG}`;

// The Sigstore identity every release asset must be signed under. Opengrep's
// binaries are produced by its GitHub Actions release workflow (keyless
// Fulcio certificates whose SAN is the workflow URL). Checked by the pin script.
export const OPENGREP_SIGNING_IDENTITY = {
  oidcIssuer: 'https://token.actions.githubusercontent.com',
  // The rolling-release workflow on main, or a tagged release workflow.
  identityRegexp:
    '^https://github\\.com/opengrep/opengrep/\\.github/workflows/[^@]+@refs/(heads/main|tags/v[0-9.]+)$',
} as const;

export type OpengrepAssetName =
  | 'opengrep_windows_x86.exe'
  | 'opengrep_manylinux_x86'
  | 'opengrep_manylinux_aarch64'
  | 'opengrep_musllinux_x86'
  | 'opengrep_musllinux_aarch64'
  | 'opengrep_osx_x86'
  | 'opengrep_osx_arm64';

export type OpengrepAssetPin = {
  // Lower-case hex SHA-256 of the exact bytes GitHub served when pinned.
  sha256: string;
  // Byte length, checked against the download before the digest so a
  // truncated transfer fails fast with a size message rather than a hash one.
  bytes: number;
};

// <opengrep-pin:assets>
// Generated by scripts/opengrep-pin.mjs for v1.30.0 (published 2026-09-07T11:20:14Z) — do not edit by hand.
// Every digest below was Sigstore-verified with cosign against OPENGREP_SIGNING_IDENTITY when pinned.
export const OPENGREP_ASSETS: Record<OpengrepAssetName, OpengrepAssetPin> = {
  'opengrep_windows_x86.exe': { sha256: 'b5cf4f8fe9f44e030aab2d579d96bd395c139db1f1ba66633676ff4d5ebc7c39', bytes: 53652992 },
  'opengrep_manylinux_x86': { sha256: '35779bdd72e92129c8df2a77f0c55e8c08356801ea92591ef32108d6b28d564c', bytes: 46516392 },
  'opengrep_manylinux_aarch64': { sha256: 'a5d5a4a58ba5d46ff51e921663da1c2bba38f4b03987f4aeec87f16c6ad3ecae', bytes: 47982360 },
  'opengrep_musllinux_x86': { sha256: 'ee21fa70714531e1eccbcb50993a871e198fb0f4ade254ef7636c433304fe4bd', bytes: 48609096 },
  'opengrep_musllinux_aarch64': { sha256: '937d0f35fc05af8877f5f34e04465f2466a8da3c33c2a0d510b8a896383354ef', bytes: 49809144 },
  'opengrep_osx_x86': { sha256: '650772a849a2986880982b7dea0371f96a75d354de95f94e8c1a2e6f8f6262d1', bytes: 48384448 },
  'opengrep_osx_arm64': { sha256: '0f5bc3dec09d995c61331a4017b856ede508f90d95b018d95f1dc6166be89fdd', bytes: 47364272 },
};
// </opengrep-pin:assets>

export type OpengrepRulePackId = 'qodana-mit' | 'opengrep-archived';

export type OpengrepRulePackDef = {
  id: OpengrepRulePackId;
  label: string;
  // git clone URL. Fetched with `git fetch --depth 1 origin <commit>` — a
  // commit is content-addressed, so checking it out verifies the tree by
  // construction (no tarball digest to pin, and tarball bytes drift anyway).
  repo: string;
  homepage: string;
  commit: string;
  // The licence the KEPT files carry after pruning.
  licence: string;
  // One-line note shown beside the pack in Settings; states any condition the
  // user should know before enabling (Commons Clause, archived, …).
  note: string;
  // Enabled for scans by default. A user can still turn a default pack off.
  defaultEnabled: boolean;
  // Top-level paths (relative to the pack root, forward slashes) removed after
  // checkout. Everything that is not a `*.yaml`/`*.yml` rule file is removed
  // regardless (test sources, CI config, scripts) — see rules.ts `prunePackTree`.
  prune: string[];
};

export const OPENGREP_RULE_PACKS: readonly OpengrepRulePackDef[] = [
  {
    id: 'qodana-mit',
    label: 'Qodana SAST rules (MIT subset)',
    repo: 'https://github.com/qodana/opengrep-sast-rules.git',
    homepage: 'https://github.com/qodana/opengrep-sast-rules',
    commit: '19af7ed20926ed0b1666e5f78722d4c0824ba99a',
    licence: 'MIT',
    note:
      'Actively maintained by JetBrains Qodana. Lattice keeps only the MIT-licensed ' +
      'rules: the LGPL-3 `rules/lgpl/` folder and the JetBrains-authored `jetbrains/` ' +
      'folder (LGPL-3 + Commons Clause) are deleted after download.',
    defaultEnabled: true,
    prune: ['jetbrains', 'rules/lgpl'],
  },
  {
    id: 'opengrep-archived',
    label: 'Archived opengrep-rules snapshot (Semgrep community rules, Dec 2024)',
    repo: 'https://github.com/opengrep/opengrep-rules.git',
    homepage: 'https://github.com/opengrep/opengrep-rules',
    commit: 'f1d2b562b414783763fd02a6ed2736eaed622efa',
    licence: 'LGPL-2.1 + Commons Clause (no resale)',
    note:
      'Frozen since 2025 (the repository is archived) but by far the broadest pack: ' +
      'the only one with real TypeScript / React / Node / Express coverage. Its LICENSE ' +
      'is LGPL-2.1 with the Commons Clause, which forbids SELLING a product whose value ' +
      'derives substantially from these rules; scanning your own code locally is fine, and ' +
      'Lattice itself stays MIT because the rules are only ever downloaded here, at your click. ' +
      'Used by scans once installed; installing it is the explicit step.',
    // Used by scans as soon as it is installed: it is the only pack with real
    // TypeScript/Node/Express coverage, and its licence condition (no resale)
    // attaches to the user of the rules, not to Lattice — see ./CLAUDE.md.
    // The DOWNLOAD stays an explicit click with the licence named on the row.
    defaultEnabled: true,
    prune: ['scripts', 'stats', 'template.yaml', 'metadata-schema.yaml.schm', 'Makefile', 'Pipfile', 'Pipfile.lock'],
  },
];

export function findRulePackDef(id: string): OpengrepRulePackDef | undefined {
  return OPENGREP_RULE_PACKS.find((p) => p.id === id);
}
